### ISSUE TITLE
Lots of actions in base connector not present in JSON

### ISSUE THREAD

**Issue by phantom-developer** [phantomcyber/reversinglabs-a1000#5]
There are 4 actions in the base connector which are not in the app JSON. At a minimum, there should at least be a "get report" action to compliment "detonate file".

**Comment by pzhou-splunk** [comment]
Hello!

This repo has been migrated to our new GitHub org. Please find a copy of this issue at https://github.com/splunk-soar-connectors/reversinglabs-a1000/issues/1
